### PR TITLE
NPM update

### PR DESCRIPTION
**Pull request by danielweck**
* NPM lockfile now aligned with r2-xxx-js packages.
* Removed r2-testapp-js dependency (not needed in readium-electron).
* Minor: added `package.json` script "package:pack-only" for `electron-builder` (a separate branch will be created later, for the customized ASAR build process)

Please merge this as soon as possible to avoid future branch conflicts :)
(if you approve, of course)

### CODE REVIEW

**Comment by danielweck** [comment]
Linux failure (TypeScript compiler / WebPack loader):
https://travis-ci.org/readium/readium-desktop/builds/393987949#L1461

Works fine on MacOS, so I compared the contents of the `node_modules` in particular the `r2-xxx-js` packages, and they seem duplicated in Linux (whereas they are correctly organised in MacOS). Same Node and NPM versions. I will try downgrading NPM, as this is usually the culprit.

**Comment by danielweck** [comment]
Downgrading from NPM `6.*` to `5.*` seems to fix this. If this is confirmed, I am going to adjust the TravisCI YAML script to ensure we can build PRs...

**Comment by danielweck** [comment]
Just as I suspected, `npm ci` works on `6.*` when used instead of `npm install`.

**Comment by danielweck** [comment]
Note that `react-dropzone` version `4.2.12` introduces a regression bug (invisible publication library, yet each cover item is in the DOM), so we stick to `4.2.11`.

**Comment by danielweck** [comment]
Note that the `react-dropzone` version `4.2.12+` regression bug still exists (invisible publication library, yet each cover item is in the DOM), so we stick to `4.2.11` (latest is `4.3.0`).
See:
https://github.com/react-dropzone/react-dropzone/issues/631

**Comment by leomoty** [comment]
`react-tap-event-plugin` is not compatible with `react` >= 16.4, nor they plan on supporting it. Found this while I was looking how to compile the project itself.

https://github.com/zilverline/react-tap-event-plugin/issues/121

**Comment by leomoty** [comment]
Also, should be a simple fix:

```
npm WARN deprecated material-ui@0.20.2: You can now upgrade to @material-ui/core
```

**Comment by danielweck** [comment]
Regarding `@material-ui/core`: just to clarify, the purpose of this PR is to ensure that the `r2-xxx-js` dependencies are up to date (which sometimes requires code changes in `readium-desktop`), and also to make sure that common / shared dependencies with `readium-desktop` are aligned. This way, the `package-lock.json` file is consistent across the board, and the dependencies expressed in `package.json` explicitly reference their actual semver (current `node_modules` packages as per the NPM lockfile).

Note that I use the NCU utility to check for the latest available versions (minor and major updates). The goal is to explicitly include minor changes (to stay in sync with security updates, bug fixes, improvements, etc.), whilst filtering-out known breaking API updates. In the latter case, the `4.x.x` semver notation is used instead of `^4.0.0` (for example) which gives developers a strong visual cue that some dependencies break the build (and it makes it easy to use NCU with its "exclude" flag, e.g. `ncu -a -u -x electron,webpack,webpack-dev-server,etc`).

So, thank you for the heads-up about `@material-ui/core`, but I think it is fine for now as the UI redesign will probably shake things quite a bit (including the Material deps). Cheers! :)

**Comment by leomoty** [comment]
@danielweck I am not really worried about the UI itself, I am trying to build the LCP stack, but so far I am not sure whether my `.lcpl` license file works or not. I tried building `readium-desktop` from source without success. The alpha binary works, but I cant seem to open the epub, nor does it echo any error that could help.

**Comment by danielweck** [comment]
@leomoty here is a copy-paste of the error you mentioned here https://github.com/readium/readium-desktop/issues/162#issuecomment-412846571 :
```
  ERROR in [at-loader] ./src/renderer/components/ReaderApp.tsx:295:33 
        TS2345: Argument of type '(docHref: string, docSelector: string) => void' is not assignable to parameter of type '(docHref: string, locator: IEventPayload_R2_EVENT_READING_LOCATION) => void'.
      Types of parameters 'docSelector' and 'locator' are incompatible.
        Type 'IEventPayload_R2_EVENT_READING_LOCATION' is not assignable to type 'string'.
    
    ERROR in [at-loader] ./src/renderer/components/ReaderApp.tsx:671:13 
        TS2345: Argument of type 'string' is not assignable to parameter of type 'IEventPayload_R2_EVENT_READING_LOCATION'.
```

Are you sure you have a clean Git local copy of the branch? (please `git pull && git status` just to make sure everything looks good)

**Comment by leomoty** [comment]
```
git pull
Already up to date.
Current branch feature/npm-update-packs is up to date.

git status
On branch feature/npm-update-packs
Your branch is up to date with 'origin/feature/npm-update-packs'.

nothing to commit, working tree clean
```

**Comment by leomoty** [comment]
Trying to clone again on Windows

```
L:\>npm --version
6.1.0

L:\>node --version
v10.6.0
```

Will report back after `npm install` runs.

**Comment by leomoty** [comment]
`npm install` is so much better:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1824 packages from 1446 contributors and audited 19709 packages in 417.952s
found 0 vulnerabilities
```

Errors have changed:

```
[2] ERROR in [at-loader] ./src/main/redux/sagas/lcp.ts:74:21
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-navigator-js/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server'.
[2]
[2] ERROR in [at-loader] ./src/main/redux/sagas/lcp.ts:135:21
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-navigator-js/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server'.
[2]
[2] ERROR in [at-loader] ./src/main/streamer.ts:37:20
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-navigator-js/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server'.
[2]
[2] ERROR in [at-loader] ./src/main/streamer.ts:51:17
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-navigator-js/node_modules/r2-streamer-js/dist/es6-es2015/src/http/server").Server'.
[2]   Types have separate declarations of a private property 'publications'.
[2]
[2] ERROR in [at-loader] ./src/renderer/components/ReaderApp.tsx:679:13
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-shared-js/dist/es6-es2015/src/models/publication").Publication' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-navigator-js/node_modules/r2-shared-js/dist/es6-es2015/src/models/publication").Publication'.
[2]   Types have separate declarations of a private property 'Internal'.
[2]
[2] ERROR in [at-loader] ./src/utils/lcp.ts:115:17
[2]     TS2345: Argument of type 'import(".../readium-desktop/node_modules/r2-shared-js/node_modules/r2-lcp-js/dist/es6-es2015/src/parser/epub/lcp").LCP' is not assignable to parameter of type 'import(".../readium-desktop/node_modules/r2-lcp-js/dist/es6-es2015/src/parser/epub/lcp").LCP'.
[2]   Types have separate declarations of a private property '_usesNativeNodePlugin'.
```
I just omitted my absolute path, everything else is verbatim.

**Comment by danielweck** [comment]
Note that I've had build failures in the past with NodeJS version `10+`, so nowadays I stick to LTS version `8` on Linux, MacOS and Windows. NPM however is latest `6.3.0` (via `npm --global update npm` after installing the official NodeJS distribution). The Electron `1.x.x` runtime is actually NodeJS `8` so this is another reason why I like to run all my `r2-streamer-js` tests on the same LTS version.

**Comment by danielweck** [comment]
Note that the `r2-xxx-js` `package.json` dependencies in `master`, `develop` and this PR branch `feature/npm-update-packs` all point to the same Git "commit-ish" reference (i.e. `develop` named branch/tag inside special "dist" repositories which are used instead of npmjs.com to publish builds):
https://github.com/readium/readium-desktop/blob/master/package.json#L127
https://github.com/readium/readium-desktop/blob/develop/package.json#L134
https://github.com/readium/readium-desktop/blob/feature/npm-update-packs/package.json#L136
...but the `package-lock.json` *actual* revision should take precedence when invoking `npm install` or `npm ci`. Seems to work fine with NPM `6+`, and used to work with v`5`.

**Comment by danielweck** [comment]
It is worth noting that TravisCI (Linux) successfully builds this PR branch `feature/npm-update-packs` using NodeJS LTS v`8.11.3` and the latest NPM v`6.3.0`.

See:
https://travis-ci.org/readium/readium-desktop/builds/415887205

**Comment by leomoty** [comment]
I am currently running `npm install` both with LTS node and latest NPM.

**Comment by leomoty** [comment]
Still getting the same error, however, running `npm list` I noticed this: 

image

image

These are not necessarily all errors, but I am under impression all yours are marked as ìnvalid`.

**Comment by leomoty** [comment]
Okay, I was able to successfully load it:

```
 npm update

+ ping@0.2.2
+ r2-shared-js@1.0.0-alpha.1
+ ta-json@2.3.0
+ r2-opds-js@1.0.0-alpha.1
+ r2-utils-js@1.0.0-alpha.1
+ r2-lcp-js@1.0.0-alpha.1
+ r2-streamer-js@1.0.0-alpha.1
+ r2-navigator-js@1.0.0-alpha.1
removed 70 packages, updated 9 packages, moved 2 packages and audited 19709 packages in 32.054s
found 0 vulnerabilities
```

It compiled now. I have no clue what is the issue, but running `npm update` fixed it.

**Comment by danielweck** [comment]
Makes sense. Not.

**Comment by leomoty** [comment]
Also, I know for sure it is my issue now, I guess:
```
[2] ## downloadContent err
```

I think some config from `config.yaml` at lcp-server README could be outdated or something, but I am not 100% sure how to define `license.links.publication`. I am currently testing with the Frontend app, by the way.

**Comment by danielweck** [comment]
Thank you for your debunking of this NPM issue. So it is now quite clear that GitHub dependencies ( as officially supported by NPM https://docs.npmjs.com/cli/install ) are problematic, requiring an extra `npm update PACKAGE_NAME` for each culprit (or a more general `npm update` which could be problematic because this would affect other non-GitHub packages, and potentially modify the `package-lock.json`)

**Comment by leomoty** [comment]
@danielweck this is not the first time I have issues with npm, which is why I guess people suggests yarn? I can't say for sure, never used it myself. I'll try to go back to make the `readium-desktop` read my encrypted epub file. Thank you!

**Comment by leomoty** [comment]
Done, https://github.com/edrlab/r2-lcp-js/issues/2

**Comment by danielweck** [comment]
I filed a separate issue regarding Material-UI:
https://github.com/readium/readium-desktop/issues/164

**Pull request merged**
