### PR TITLE
JSON locale checking (requires canonical key sorting), discovered lots of missing German keys, and a few redundant

### PR DESCRIPTION
**Pull request by danielweck**
Fixes https://github.com/readium/readium-desktop/issues/397

Fixes https://github.com/readium/readium-desktop/issues/476

### CODE REVIEW

**Comment by danielweck** [comment]
@panaC the part that is now missing is the scanning of source code (AST or regexp, whichever works reliably) in order to discover all the localization keys, and verify that the primary `en` locale contains them (no missing, no redundant keys). The secondary locales can be verified against the primary easily using the utilities in this PR.
So, have you made any progress with regards to searching the source code for all the keys?

**Comment by danielweck** [comment]
I am happy to report that `en` and `fr` are well-aligned (no missing keys, no unused keys). However `de` is in bad shape, as shown in this commit:
https://github.com/readium/readium-desktop/pull/506/commits/efa423a859042592160a37d93e9fcb26db00aec0
(tip: search for all empty strings `""`, and this returns all the missing locale keys)

**Comment by danielweck** [comment]
Note that in order to deal with empty string values `""` which indicate missing JSON keys (there are many in the German `de` locale), I patched the translator code:

https://github.com/readium/readium-desktop/pull/506/commits/f50a234b2e5a0945ee000cc699fefa92dc587aa4

Now we have consistent fallback to English when there are missing keys, or when the values are empty strings.

**Comment by danielweck** [comment]
I created a separate issue about scanning the source code: https://github.com/readium/readium-desktop/issues/509

**Comment by danielweck** [comment]
Hello Pierre @panaC could you please send me your thoughts / review on this PR, I would like to merge it early so that any upcoming addition to the locales is based on the cleaned-up format (checked JSON keys) Thank you! :)

**Comment by panaC** [comment]
No problems, I'm always in seeking a solution to correctly parse the source code locale

Just a question: why use yarn and not npm ?

**Comment by danielweck** [comment]
Ah thank you, `yarn` usage slipped through the net! (from another project) I will correct that immediately :)

**Comment by danielweck** [comment]
Ok, I am going to merge.
I will also file an issue about replacing (in a future revision) the current shell script which creates a canonical / key-sorted version of the locale JSONs, with a cross-platform NodeJS solution (hopefully a simple one-liner NPM script based on an existing package). The reason behind using the native shell / CLI utility (which is itself cross-platform, but requires external install) was to rely on a well-tested implementation, so that our locales do not get screwed-up by some version `0.0.x` lib found on NPM ;)

**Comment by danielweck** [comment]
New issue about canonical JSON key sorting (replace `jq` shell executable):
https://github.com/readium/readium-desktop/issues/514

**Comment by danielweck** [comment]
New issue specifically about the missing German keys:
https://github.com/readium/readium-desktop/issues/515

**Pull request merged**
