### PR TITLE
Move the about section in the main page

### PR DESCRIPTION
**Pull request by Scarsniik**
fixe issue #303

### CODE REVIEW

**Comment by danielweck** [comment]
The "about Thorium" / "more information" section is located below the bookshelf, at the very bottom. It is not easily discoverable / reachable once publications are imported. Is that okay? (see screenshots)

ThoriumAbout1

... scroll ... (or keyboard-tab)

ThoriumAbout2

**Comment by danielweck** [comment]
* The "more information" box does not evidently look like a modal popup dialog, because of the lack of left/right margins.
* There is a vertical scrollbar in the main app area, which should not exist (needs overflow hidden?)
* The information text is horizontally-centered, which makes the bullet points look very awkward (I suggest left-align, or justify).

See screenshot:

ThoriumAbout3

**Comment by llemeurfr** [comment]
Yes this is what I requested to Leo. I didn’t want it to bloat the navigation bar and didn’t want it to stay in Settings (it is not). 
We may rethink that later but for now it solves a large accessibility issue we had before. And people scroll. 

My only remark so far : the alignment of the elements is discutable, as is the Lack of space between the carousel and the title of the section.

**Comment by llemeurfr** [comment]
And I agree with Daniel’s comments about the modal window.

**Comment by danielweck** [comment]
When the "more information" dialog is closed (escape-key or cross-button-click or mouse-click-outside), the keyboard focus should return to the calling site (button).

**Comment by danielweck** [comment]
There is now a code conflict (please synchronize with the tip of the develop branch :)

**Comment by danielweck** [comment]
Side note -- I have found "about-window" pretty useful (other Electron projects):
https://github.com/rhysd/electron-about-window#screen-shots

...but it is only good for short content (description summary, copyright, version(s), links).

So, although it would partly solve the "viewport" problem, it does not solve the "calling site" issue (in other projects, there is a menu bar with an "about" menu item).

**Comment by llemeurfr** [comment]
I'd like to see "V1.0.0-beta.2"

**Pull request merged**
