### PR TITLE
changing reader theme skins it

### LINKED ISSUE #83: night/dark mode in ReadiumCSS (EPUB HTML content documents) should be matched in UI

### PR DESCRIPTION
**Pull request by Scarsniik**
Fixes #83 and #295

### CODE REVIEW

**Comment by danielweck** [comment]
I searched for the character `#` inside the codebase, with file filter `*.css,*.svg` (using Visual Studio Code). There are many instances of RGB color codes (`#xxyyzz`).
Same remark when searching for `rgb` (e.g. `rgba(0, 0, 0, 0.1)` / `rgb(0, 188, 212)`).

Is that an oversight, or a deliberate design choice?

**Comment by Scarsniik** [comment]
When I need transparency I prefere to use rgba because I think it's more readable but otherwise I use hexa code

**Comment by danielweck** [comment]
Sorry, my original question was not clear: I was in fact wondering why are there so many hard-coded colour values, when the goal is to parametrize the CSS styles with variables / custom properties? (so that we can apply consistent dark / light theming across the entire UI)

**Comment by Scarsniik** [comment]
Oh, ok. It's from the original integration we used at the begining. There was no variable so I didn't used id but in this PR I replaced a lot of hard coded color with variable.

**Comment by danielweck** [comment]
So, you are satisfied with all the hard-coded colours that remain? (personally I do not know for sure, this is why I am asking :)

Just to double-check, could you please run a search for `#` and `rgb` inside the codebase, with the file filter `*.css,*.svg`. Then, if you are satisfied that none of the hard-coded colours need to be changed into dark/light variables, I will be happy to merge this PR based on your judgement (for me, it is quite hard to judge because I do not know the CSS/SVG styles in-depth)

**Comment by Scarsniik** [comment]
Yes, I didn't change some values but I think themes I made are good. The hard coded colors was working with all the themes, it's why I keep them

**Comment by danielweck** [comment]
Thanks, LGTM!

**Comment by Sarvasri** [comment]
BlueFire reader on iOS (and perhaps other platforms) offers sliding controls for text and background color for both light and dark mode. This would be a good example to review. Years ago, Stanza offered the best EPUB reader with great controls. One great advantage of EPUB over PDF is the ability to customize the reading experience. This is so basic, yet it is not offered in many apps. I've been looking for a reader for desktop for a long time for Mac that offers a customizable UI. Thorium has good typography, but minimal user control of the reading experience. There should be a brightness control. Background texture selection would be nice. Colors for text and background for light and dark mode.

**Pull request merged**
