### PR TITLE
NPM updates and convertMultiLangStringToString() for Subject.Name

### PR DESCRIPTION
**Pull request by danielweck**
Tested with OPDS2 Feedbooks feed:
https://catalog.feedbooks.com/catalog/index.json

...as well as OPDS1:
https://www.feedbooks.com/catalog.atom

### CODE REVIEW

**Comment by danielweck** [comment]
I have now updated this PR with the latest `r2-xxx-js` packages.

* You will see the addition of a "popup footnotes" boolean flag in the ReadiumCSS object (currently using the default value, so feel free to add a user setting + UI in readium-desktop if you wish ... or you can leave this feature as default for now).

* You will also see a minor change regarding the initial fetch() URL of the publication manifest.json (in the renderer process, now there is no need to invoke special Electron privileges)

**Comment by danielweck** [comment]
This PR also fixes https://github.com/readium/readium-desktop/issues/205

**Comment by danielweck** [comment]
Hello @clebeaupin is there anything specific blocking this Pull Request, anything I can do to help merge?

**Comment by danielweck** [comment]
Alright, so some of this PR's code diffs were cherry-picked / adopted separately into `feature/new-db`, so I have now resolved the (minor) merged conflicts, and I synchronized this PR to match the latest merge destination `feature/new-db` :)

As you can see the current code diff now contains:

* the fix for this fatal issue (complete app crash): https://github.com/readium/readium-desktop/issues/205
* and a minor change regarding the initial fetch() URL of the publication manifest.json (in the renderer process, now there is no need to invoke special Electron privileges .. just use the regular localhost HTTP URL instead)
* NPM updates

LGTM! :)

**Comment by danielweck** [comment]
This PR is still open, so I am taking the opportunity to update the `r2-navigator-js` package :)
Feel free to merge, I have no pending updates.

**Comment by clebeaupin** [comment]
This Merge Request is very old and all the changes have been already integrated in develop branch.
So I close it

**Pull request closed without merging**
